### ISSUE TITLE
Show main pages completely failing to load.

### ISSUE THREAD

**Issue by 0r1ce** [jerry08/Anikin#30]
### Summary

The "main pages"(where each show's episodes are presented) doesnt load, and after some time, the app even crashes.  Happened to me only on the gogoanime source. Have tried restarting both my device and the app but to no avail.

### Steps to reproduce

- go to the Gogoanime source
- try and click on any show

https://github.com/jerry08/Anikin/assets/145497364/d422ce39-285a-4356-803a-6522b1dad537

https://github.com/jerry08/Anikin/assets/145497364/b47f797b-5d3f-49fe-a820-632af98ec654

### Expected Result

The anime page is expected to load, if after a short while or otherwise.

### Actual Result

The show completly fails to load, and, ocationally, can even out right crash the app after a significant loading time. Only replicable on gogoanime.

### Device Information

Galaxy A50
Model num: SM-A505F
Android version: 11
Anistream version: 1.9.92

### Checklist

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have made sure that that this bug is reproducible on the latest version of the application.
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible.

### Additional Information

Love the app, hope this can be fixed.

**Comment by jerry08** [comment]
This is not an issue with the app. Gogoanime server had an internal error. It's working again now.
