### ISSUE TITLE
No videos found + no servers found

### ISSUE THREAD

**Issue by tyrell-wallace** [jerry08/Anikin#36]
### Summary

No videos load, no servers are found

### Steps to reproduce

Download the program either for android or windows, and try to load any video.
The same exception happens for all anime I tried. I couldn't copy the text so I'll attach a screenshot.
![error](https://github.com/user-attachments/assets/a2f09dfe-cc46-408a-a7e4-362c0cdc0626)

### Expected Result

For it to load the videos.

### Actual Result

No videos were loaded and no servers appear.

### Device Information

Android 13 and Windows 10.

### Checklist

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have made sure that that this bug is reproducible on the latest version of the application.
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible.

**Comment by flawlessgoku** [comment]
the fix to this problem is in discord server

**Comment by flawlessgoku** [comment]
please always refer to discord server before making these

**Comment by tyrell-wallace** [comment]
> the fix to this problem is in discord server
I'll take a look, thanks.

**Comment by tyrell-wallace** [comment]
> > the fix to this problem is in discord server
> 
> I'll take a look, thanks.

Forgot to give a follow up: the discord invite is broken.
